### ISSUE TITLE
problems on building

### ISSUE THREAD

**Issue by herocbn** [NREL/SOEP-QSS#5]
I am a green finger on how to build this poject, how can i get detailed operations？

**Comment by DeadParrot** [comment]
Start with the Building QSS <https://github.com/NREL/SOEP-QSS#building-qss> section of the README and then let me know what, if any, problems you run into.

For the FMI Library I suggest getting version 2.4.1 from https://github.com/modelon-community/fmi-library/releases/tag/2.4.1. If you have trouble building or using it (use the same compiler as you choose for QSS) just ask.

**Comment by herocbn** [comment]
hello， when i build FMI，running the followings 

mkdir build-fmil; cd build-fmil
cmake -FMILIB_BUILD_STATIC_LIB=../../custom      ../../custom.Linux/ 
make install test

I run into error, what shoud I do here?
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/694fdaeb-4cc7-4e97-8d9d-ee2126a76407)

**Comment by herocbn** [comment]
I guess I misunderstand the two parameters
_prefix_    
 _path to FMIL source_ 
can someone help me ?
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/4481620e-e5aa-4af9-8859-e696b99c372f)

**Comment by DeadParrot** [comment]
The cmake line would look something like:
```
cmake -DFMILIB_INSTALL_PREFIX=/home/<user>/libs/FMIL /home/<user>/code/FMIL
```
- The path to FMIL source should point to the root FMIL repository directory (above the `src` directory).
- Run `cmake` and `make` with sudo if the install path is not within an owned directed, for example `/opt/FMIL`.
- Especially if you are doing a release build you may not want/need to pass `test` to make.

**Comment by herocbn** [comment]
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/a5e75561-aab5-43cf-b655-13c7029508aa)
here, the steps are a little confusing, i am using Linux

**Comment by DeadParrot** [comment]
Once you are able to build FMIL directly I'd recommend using the scripts and code under the `FMIL` directory of this repository to do build an FMIL ready for QSS usage, especially adding all the extra headers QSS needs.

This would mean copying the FMIL repository source code into a `FMIL/custom` directory, merging the changes in `custom.Linux` over that, and then using the build scripts in `bin` to build the FMIL, such as `FMIL/bin/bld.GCC.r.sh` (`r` is for the release build). These scripts are set up to install to directories of the form: `/opt/FMIL.<compiler>.<build>` so if you want to put FMIL somewhere else you'll need to customize the scripts.

**Comment by herocbn** [comment]
OK，thks，when i do mak command as follow:
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/2ae99eeb-766e-4e42-8cb4-2888f9488e5e)
i cannot get any information about the  progress, is that correct?

**Comment by DeadParrot** [comment]
You should see each source compiling and the libQSS.a library build command and then the QSS executable linking. If nothing is happening then there is a problem. You can try adding `-d` to the `mak` command to get debugging output from make. You can also run the `bld` command instead of `mak` to get more environment setup/checks before it runs `mak`. You have to do the builds from a console configured with the desired `setQSS` script, such as `source bin/Linux/GCC/r/setQSS`, as the build instructions specify.

**Comment by herocbn** [comment]
when i run mak -d as you say 
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/de38958e-5ad8-4ee2-b3ac-adae2429deec)
it seems deadlock?

**Comment by herocbn** [comment]
Here is the detailed information, when i run mak -d
[debug.txt](https://github.com/NREL/SOEP-QSS/files/11973872/debug.txt)

**Comment by DeadParrot** [comment]
It looks like you didn't use FMIL 2.4.1 -- you have failures for headers of the form `fmi3_*.h` and those are from the latest FMIL master branch where they have started adding FMI 3.0 support. QSS doesn't use FMI 3.0 and the FMIL support isn't yet updated to work with the latest FMIL master branch. Try deleting your FMIL install directory `/opt/FMIL.GCC.r`, checking out the 2.4.1 tag revision from the FMIL Library git repository and then following the instructions in `FMIL/README.md`  for merging the `custom.Linux` modifications into a copy of that code and then building that FMIL. If you get that right there should be no `fmi3_*.h` headers under `/opt/FMIL.GCC.r` and then I think/hope your QSS build will succeed.

Please also make sure:
- You are using the latest revision of SOEP-QSS unless you have a specific reason to use an older one
- g++ is installed and on your PATH (and you can build a small test C++ application)
- Python 3.8+ is installed and on your PATH
- You adapt the build setup if you use a different FMIL install directory or you are using an old Ubuntu or g++ that doesn't support some of the C++ usage in QSS

**Comment by herocbn** [comment]
Hello,  i run into the last step
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/b53c9f27-acef-4eac-aa39-c1dcc8c34991)
and in /opt/FMIL.GCC.r/lib 
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/9f5cf70d-490b-4591-882d-9e3b9a584631)
what's wrong?

**Comment by DeadParrot** [comment]
Since you don't show your full environment and the full command and output (text is better than a screenshot) I can only guess that you not using the custom.Linux changes when you build FMIL, which includes turning `FMILIB_INSTALL_SUBLIBS` on in CMakeLists.txt.

**Comment by herocbn** [comment]
thank u， i make it！
