### ISSUE TITLE
About building FMU-QSS

### ISSUE THREAD

**Issue by herocbn** [NREL/SOEP-QSS#6]
![image](https://github.com/NREL/SOEP-QSS/assets/92193912/6d5fa070-7011-4de6-9e82-f77466ad8845)
when i run above, it occurs an error, is there anything wrong?

**Comment by DeadParrot** [comment]
The FMU-QSS support is not currently in use by our project so it wasn't up to date. I updated it to match the current code base so please give it a try now.

Unless you want to use QSS on multiple, connected FMU-ME FMUs the FMU-QSS support won't be useful.

**Comment by herocbn** [comment]
OK， thanks

**Comment by herocbn** [comment]
Hello, now, i have a modelica model , how can i simulate my model with this solver ? please give me some ideas.

**Comment by herocbn** [comment]
another issue ：i pull your latest version， when building， it failed.
errors like : 
/home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: error: dependent-name ‘QSS::Observers<V>::Variables::size_type’ is parsed as a non-type, but instantiation yields a type
 1075 |   for ( Variables::size_type i = 0, e = qss_observees_.size(); i < e; ++i ) { // Set observee directional derivative vector
      |                                                              ^
/home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: note: say ‘typename QSS::Observers<V>::Variables::size_type’ if a type is meant

**Comment by herocbn** [comment]
another issue ：i pull your latest version， when building， it failed.
errors like :
```
/home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: error: dependent-name 
/‘QSS::Observers::Variables::size_type’ is parsed as a non-type, but instantiation yields a type
1075 | for ( Variables::size_type i = 0, e = qss_observees_.size(); i < e; ++i ) { // Set observee directional derivative vector
| ^
/home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: note: say ‘typename QSS::Observers::Variables::size_type’ if a type is meant
```

**Comment by DeadParrot** [comment]
> Hello, now, i have a modelica model , how can i simulate my model with this solver ? please give me some ideas.

The current SOEP-QSS is designed to work with FMUs built from Modelica models using Modelon's latest Optimica Compiler Toolkit that has some options/features for QSS. (Earlier revisions of this repository could work, with limitations, with JModelica or Dymola.)

This information is in the README.md file.

**Comment by DeadParrot** [comment]
> another issue ：i pull your latest version， when building， it failed. errors like :
> 
> ```
> /home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: error: dependent-name 
> /‘QSS::Observers::Variables::size_type’ is parsed as a non-type, but instantiation yields a type
> 1075 | for ( Variables::size_type i = 0, e = qss_observees_.size(); i < e; ++i ) { // Set observee directional derivative vector
> | ^
> /home/cbn/Desktop/project/SOEP-QSS/src/QSS/Observers.hh:1075:62: note: say ‘typename QSS::Observers::Variables::size_type’ if a type is meant
> ```

This is corrected in the current master branch. The Visual C++ and Intel C++ compilers on Windows (unlike GCC) are lax about places like this where `typename` is technically required.

**Comment by herocbn** [comment]
ok， thanks a lot !
